package:
  name: pytide
  version: 1.0.0

source:
    git_url: https://github.com/CNES/pangeo-pytide.git
    git_rev: HEAD

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - eigen
    - numpy
    - python {{ python }}
    - setuptools
  run:
    - numpy
    - python {{ python }}

test:
  imports:
    - pytide